# .github/workflows/git-sync.yml
name: Sync Repository to MindsSpace Organization
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  git-sync:
    if: ${{ github.repository == 'lintangcahyaaa/mindspace-model' }}
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://robbypambudi:${{secrets.ACCESS_TOKEN}}@github.com/lintangcahyaaa/mindspace-model.git"
          source_branch: "main"
          destination_repo: "https://robbypambudi:${{secrets.ACCESS_TOKEN}}@github.com/MindsSpace/mindspace-model.git"
          destination_branch: "main"
