name: Upload Model to GCS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  job_id:
    if: ${{ github.repository == 'lintangcahyaaa/mindspace-model' }}
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        id: "checkout"
        uses: "actions/checkout@v4"

      - name: Authenticate with Google Cloud
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          service_account: "model-viewer@mindspace-capstone-project.iam.gserviceaccount.com"

      - name: Upload model to GCS
        id: "upload-folder"
        uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          path: "models"
          destination: "mindspace-model"
